config/routes.rb
Rails.application.routes.draw do
  resources :streams
  root to: 'home#index'
  get 'submit', to:'pages#submit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def submit

  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :set_stream, only: %i[ show edit update destroy ]

  # GET /streams or /streams.json
  def index
    @streams = Stream.all
  end

  # GET /streams/1 or /streams/1.json
  def show
  end

  # GET /streams/new
  def new
    @stream = Stream.new
  end

  # GET /streams/1/edit
  def edit
  end

  # POST /streams or /streams.json
  def create
    @stream = Stream.new(stream_params)

    respond_to do |format|
      if @stream.save
        format.html { redirect_to stream_url(@stream), notice: "Stream was successfully created." }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1 or /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to stream_url(@stream), notice: "Stream was successfully updated." }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1 or /streams/1.json
  def destroy
    @stream.destroy

    respond_to do |format|
      format.html { redirect_to streams_url, notice: "Stream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stream_params
      params.require(:stream).permit(:competition, :home_team, :away_team, :date, :tip_time, :stream_link, :live_stats_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand" href="/">Tournaments App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Submit your stream',   new_stream_path, class:"btn btn-warning" %>
<!--        <button type="button" class="btn btn-warning">Envía tu live stream</button>-->
      </li>
    </ul>
<form class="form-inline my-2 my-lg-0">
<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>
</nav>

app/views/home/index.html.erb
<h1>Submit your Livestream</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>Tournament App</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'home/header' %>
  <div class="container pb-3">
    <br>
    <%= yield %>
  </div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/submit.html.erb
<h1>Upload your Livestream</h1>

app/views/streams/_form.html.erb
<%= form_with(model: stream) do |form| %>
  <% if stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stream.errors.count, "error") %> prohibited this stream from being saved:</h2>

      <ul>
        <% stream.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :competition %>
    <%= form.text_field :competition %>
  </div>

  <div class="field">
    <%= form.label :home_team %>
    <%= form.text_field :home_team %>
  </div>

  <div class="field">
    <%= form.label :away_team %>
    <%= form.text_field :away_team %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :tip_time %>
    <%= form.time_select :tip_time %>
  </div>

  <div class="field">
    <%= form.label :stream_link %>
    <%= form.text_field :stream_link %>
  </div>

  <div class="field">
    <%= form.label :live_stats_link %>
    <%= form.text_field :live_stats_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/streams/edit.html.erb
<h1>Editing Stream</h1>

<%= render 'form', stream: @stream %>

<%= link_to 'Show', @stream %> |
<%= link_to 'Back', streams_path %>

app/views/streams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Streams</h1>

<table>
  <thead>
    <tr>
      <th>Competition</th>
      <th>Home team</th>
      <th>Away team</th>
      <th>Date</th>
      <th>Tip time</th>
      <th>Stream link</th>
      <th>Live stats link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @streams.each do |stream| %>
      <tr>
        <td><%= stream.competition %></td>
        <td><%= stream.home_team %></td>
        <td><%= stream.away_team %></td>
        <td><%= stream.date %></td>
        <td><%= stream.tip_time %></td>
        <td><%= stream.stream_link %></td>
        <td><%= stream.live_stats_link %></td>
        <td><%= link_to 'Show', stream %></td>
        <td><%= link_to 'Edit', edit_stream_path(stream) %></td>
        <td><%= link_to 'Destroy', stream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stream', new_stream_path %>

app/views/streams/new.html.erb
<h1>New Stream</h1>

<%= render 'form', stream: @stream %>

<%= link_to 'Back', streams_path %>

app/views/streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Competition:</strong>
  <%= @stream.competition %>
</p>

<p>
  <strong>Home team:</strong>
  <%= @stream.home_team %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @stream.away_team %>
</p>

<p>
  <strong>Date:</strong>
  <%= @stream.date %>
</p>

<p>
  <strong>Tip time:</strong>
  <%= @stream.tip_time %>
</p>

<p>
  <strong>Stream link:</strong>
  <%= @stream.stream_link %>
</p>

<p>
  <strong>Live stats link:</strong>
  <%= @stream.live_stats_link %>
</p>

<%= link_to 'Edit', edit_stream_path(@stream) %> |
<%= link_to 'Back', streams_path %>